[build]
  command = "npm run build"
  publish= ".next"
[build.environment]
  SECRETS_SCAN_OMIT_KEYS = "NEXT_PUBLIC_CMS_API_KEY,NEXT_PUBLIC_CMS_DOMAIN,NEXT_PUBLIC_TURNSTILE_SITE_KEY"
[[plugins]]
  package = "@netlify/plugin-nextjs"
[[plugins]]
  package = "netlify-plugin-cache-nextjs"
